services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.1
    restart: unless-stopped
    container_name: homepage
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: abhighosh.co.uk # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    networks:
      proxy:
        aliases:
          - homepage

networks:
  proxy:
    external: true
    name: proxy
