---
- glances:
    url: http://glances-pi:61208
    version: 4
    label: Pi
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    disk: /hostfs/hostname
    unit: metric

- glances:
    url: http://100.91.21.72:61208
    username: "{{HOMEPAGE_FILE_GLANCES_USERNAME}}"
    password: "{{HOMEPAGE_FILE_GLANCES_PASSWORD}}"
    version: 4
    label: Ubuntu NAS
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    # This bind mount resides on the NAS's dedicated Frigate recording HDD.
    disk: /hostfs/frigate
    unit: metric

- datetime:
    text_size: md
    locale: en-GB
    format:
      dateStyle: medium
      timeStyle: short
      hourCycle: h23

- search:
    provider: google
    target: _blank
